feat: current action persistence on abrupt shutdowns
bytebeamio/uplink pull request #216
Opened 2023-04-27 15:51 UTC by de-sh

Closes #

### Changes

### Why?
Allows the user's application to trigger a shutdown in uplink while ensuring persistence of current action information. This is necessary to support OTA updates that might require uplink to be shutdown between action being started and action completion.

### Trials Performed

1. start uplink connected to port 5555 by an application that handles the "lock" action, and takes a long time to complete.
```
...
    tcp applications:
        name: "1"
        port: 5555
        actions: [ActionRoute { name: "lock", timeout: 300 }]
...
  2023-04-27T15:27:22.645246Z  INFO uplink::base::mqtt: Action = Action { device_id: None, action_id: "345", kind: "process", name: "lock", payload: "{}" }

  2023-04-27T15:27:22.645363Z  INFO uplink::base::bridge: Received action: Action { device_id: None, action_id: "345", kind: "process", name: "lock", payload: "{}" }

  2023-04-27T15:27:22.645414Z  INFO uplink::base::bridge: Action response = ActionResponse { action_id: "345", device_id: None, sequence: 0, timestamp: 1682609242645, state: "Received", progress: 0, errors: [], done_response: None }
...
```
2. From elsewhere, trigger a shutdown a second or two after above logs
```
#Terminal2:
 curl -X POST http://localhost:3333/shutdown
...
#Terminal1:
  2023-04-27T15:39:34.944052Z  INFO uplink::apis: Shutting down uplink

  2023-04-27T15:39:34.944181Z  INFO uplink::base::bridge: Storing current action in persistence; path: /tmp/uplink/current_action
```
3. Restart uplink
```
  2023-04-27T15:51:25.615515Z  INFO uplink::base::bridge: Loading saved action from persistence; action_id: 345
```

2023-04-28 04:25 UTC, amokfa commented
This won't save current action on device reboot. We can use this https://rust-cli.github.io/book/in-depth/signals.html

2023-04-28 09:17 UTC, de-sh commented
Experimented on this here: https://github.com/bytebeamio/uplink/compare/abrupt-shutdown...signals?expand=1

2023-05-22 10:08 UTC, tekjar requested changes

2023-05-22 10:08 UTC, tekjar commented on uplink/src/base/serializer/mod.rs
> +                std::fs::create_dir_all(&path).map_err(|_| {
Check if uplink is exiting with good error message during this case

2023-05-22 10:08 UTC, tekjar commented on uplink/src/base/serializer/mod.rs
> +                std::fs::create_dir_all(&path).map_err(|_| {
Create `negative cases` section in QA doc and add

- Unable to access persistence path
- Unable to create a dir
- Config file not available 
- Auth file not available
- Config fiile/Auth file is not valid json or toml

2023-05-22 10:32 UTC, merged